# Generated by Django 4.2.5 on 2023-10-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_do_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uqid', models.CharField(max_length=50)),
                ('to_do', models.CharField(max_length=150)),
                ('dele', models.BooleanField(default=False)),
                ('isco', models.BooleanField(default=False)),
            ],
        ),
    ]
